version: "3.3"

services:
#   db:
#     image: postgres
#     env_file:
#       - .postgres
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
